package pojo;
// Generated Oct 6, 2021 11:50:33 AM by Hibernate Tools 4.3.1

import DAO.DAOPelanggan;
import java.util.List;
import javax.faces.bean.ManagedBean;

@ManagedBean


/**
 * TblPelanggan generated by hbm2java
 */
public class TblPelanggan  implements java.io.Serializable {


     private String idPelanggan;
     private String nama;
     private String alamat;
     private String noTelp;
     private String email;
     private String jasa;
     private String harga;
     private Boolean item_error;
     private Boolean item_msg;
     private String main_error;
     private String main_msg;

    public TblPelanggan() {
    }

    public TblPelanggan(String idPelanggan, String nama, String alamat, String noTelp, String email, String jasa, String harga) {
       this.idPelanggan = idPelanggan;
       this.nama = nama;
       this.alamat = alamat;
       this.noTelp = noTelp;
       this.email = email;
       this.jasa = jasa;
       this.harga = harga;
    }
   
    public String getIdPelanggan() {
        return this.idPelanggan;
    }
    
    public void setIdPelanggan(String idPelanggan) {
        this.idPelanggan = idPelanggan;
    }
    public String getNama() {
        return this.nama;
    }
    
    public void setNama(String nama) {
        this.nama = nama;
    }
    public String getAlamat() {
        return this.alamat;
    }
    
    public void setAlamat(String alamat) {
        this.alamat = alamat;
    }
    public String getNoTelp() {
        return this.noTelp;
    }
    
    public void setNoTelp(String noTelp) {
        this.noTelp = noTelp;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getJasa() {
        return this.jasa;
    }
    
    public void setJasa(String jasa) {
        this.jasa = jasa;
    }
    public String getHarga() {
        return this.harga;
    }
    
    public void setHarga(String harga) {
        this.harga = harga;
    }

    public Boolean getItem_error() {
        return item_error;
    }

    public void setItem_error(Boolean item_error) {
        this.item_error = item_error;
    }

    public Boolean getItem_msg() {
        return item_msg;
    }

    public void setItem_msg(Boolean item_msg) {
        this.item_msg = item_msg;
    }

    public String getMain_error() {
        return main_error;
    }

    public void setMain_error(String main_error) {
        this.main_error = main_error;
    }

    public String getMain_msg() {
        return main_msg;
    }

    public void setMain_msg(String main_msg) {
        this.main_msg = main_msg;
    }
    public void save() {
        item_error = false;
        item_msg = false;
        main_error = "";
        main_msg = "";
        DAOPelanggan plg = new DAOPelanggan();
        List<TblPelanggan>  cst = plg.getbyID(idPelanggan);
        if (cst.size() > 0) {
            item_error = true;
            main_error = "MAAF, ID SUDAH ADA!";
        }else {
            DAOPelanggan oplg = new DAOPelanggan();
            plg.addPelanggan(this);
            item_msg = true;
            main_msg = "DATA BERHASIL DISIMPAN!";
            nama  = "";
            alamat  = "";
            email  = "";
            noTelp  = "";
            idPelanggan  = "";
            jasa = "";
            harga = "";
    }
    }
    
    public void reset() {
            nama = "";
            alamat  = "";
            email  = "";
            noTelp  = "";
            idPelanggan  = "";
            jasa = "";
            harga = "";
        
    }
    
    public void delete() {
        item_error = false;
        item_msg = false;
        main_error = "";
        main_msg = "";
        
        DAOPelanggan plg = new DAOPelanggan();
        plg.deletePelanggan(idPelanggan);

        nama  = "";
        alamat  = "";
        email  = "";
        noTelp  = "";
        idPelanggan  = "";
        jasa = "";
        harga = "";
        
        item_error = true;
        main_msg = "Data Berhasil Dihapus!";
        
    }
    
    public String getbyid(){
        nama  = "";
        alamat  = "";
        email  = "";
        noTelp  = "";
        jasa = "";
        harga = "";
        item_error = false;
        item_msg = false;
        main_error = "";
        main_msg = "";
        
        
        DAOPelanggan plg = new DAOPelanggan();
        List<TblPelanggan>  cst = plg.getbyID(idPelanggan);
        System.out.println(cst.size()+" Inilah Panjangnya");
        if (cst.size() > 0) {
            TblPelanggan inp = cst.get(0);
        nama = inp.getNama();
        alamat = inp.getAlamat();
        email = inp.getEmail();
        noTelp = inp.getNoTelp();
        jasa = inp.getJasa();
        harga = inp.getHarga();
        idPelanggan = inp.getIdPelanggan();
        return "view_pelanggan";
        }else {
            item_error = true;
            main_msg = "Maaf, Data Tidak Ditemukan!";
        }
         return "view_pelanggan";
        
    }
    
    public List<TblPelanggan> getallrecords() {
        DAOPelanggan plg = new DAOPelanggan();
        List<TblPelanggan> cst = plg.retrieveTblPelanggan();
        return cst;
    }
    
    public void update() {
        item_error = false;
        item_msg = false;
        main_error = "";
        main_msg = "";
        
        DAOPelanggan plg = new DAOPelanggan();
        plg.updatePelanggan(this);

        nama  = "";
        alamat  = "";
        email  = "";
        noTelp  = "";
        jasa = "";
        harga = "";
        idPelanggan  = "";
        
        item_error = true;
        main_msg = "Data Berhasil Diperbarui!";
        
    }




}


