package pojo;
// Generated Oct 6, 2021 11:50:33 AM by Hibernate Tools 4.3.1

import javax.faces.bean.ManagedBean;
import DAO.DAOLogin;
import java.util.List;

@ManagedBean


/**
 * TblUser generated by hbm2java
 */
public class TblUser  implements java.io.Serializable {


     private Integer idUser;
     private String username;
     private String password;
     private String role;
     private String output_msg;
     private Boolean output_error;

    public TblUser() {
    }

    public TblUser(String username, String password, String role) {
       this.username = username;
       this.password = password;
       this.role = role;
    }
   
    public Integer getIdUser() {
        return this.idUser;
    }
    
    public void setIdUser(Integer idUser) {
        this.idUser = idUser;
    }
    public String getUsername() {
        return this.username;
    }
    
    public void setUsername(String username) {
        this.username = username;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public String getRole() {
        return this.role;
    }
    
    public void setRole(String role) {
        this.role = role;
    }

    public String getOutput_msg() {
        return output_msg;
    }

    public void setOutput_msg(String output_msg) {
        this.output_msg = output_msg;
    }

    public Boolean getOutput_error() {
        return output_error;
    }

    public void setOutput_error(Boolean output_error) {
        this.output_error = output_error;
    }
    
    public String validasiLogin(){
        DAOLogin uDao = new DAOLogin();
        List<TblUser> us = uDao.getBy(username, password);
        System.out.println(us);
        if (us.size() == 1) {
            username = us.get(0).username;
            password = us.get(0).password;
            role = us.get(0).role;
            System.out.println("Berhasil!");
            
        return "view_pelanggan";
        }
        output_error = true;
        output_msg = "Username atau Password Anda Salah!";
        System.out.println("GAGAL!");
        return "index";
    }




}


